apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: limitry
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: limitry
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'limitry'
        static_configs:
          - targets: ['limitry.limitry.svc.cluster.local:8000']
